// netlify/functions/createVisitorDocument.js

const { MongoClient, ServerApiVersion } = require('mongodb');
const crypto = require('crypto');

const uri = process.env.MONGODB_ENV_VAR_CAN_YOU_BEAT_THE_MARKET;
const client = new MongoClient(uri, {
  serverApi: {
    version: ServerApiVersion.v1,
    deprecationErrors: true,
  },
});

// We'll create a new document on each page load.
// (We are not using a composite key; instead, each document gets its own _id generated by MongoDB.)
// We store the visitor's hashed IP in the field "visitorFingerprint".

// Function to hash the IP address using SHA-256.
const hashIP = (ip) => {
  return crypto.createHash('sha256').update(ip).digest('hex');
};

// Function to extract the user's IP from the request headers.
const getUserIP = (event) => {
  const headers = event.headers;
  // Use the appropriate header (Netlify usually provides 'x-nf-client-connection-ip' or 'x-real-ip').
  return headers['x-nf-client-connection-ip'] || headers['x-real-ip'] || '0.0.0.0';
};

exports.handler = async (event, context) => {
  // Only allow POST requests.
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ message: 'Method Not Allowed' }),
    };
  }
  
  try {
    // Connect to MongoDB if not already connected.
    await client.connect();

    // Determine the correct database name based on deploy context.
    const defaultDbName =
      process.env.CONTEXT === 'deploy-preview'
        ? 'canyoubeatthemarket-test'
        : 'canyoubeatthemarket';
    const dbName = process.env.MONGODB_DB_NAME || defaultDbName;
    const database = client.db(dbName);
    const visitorsCollection = database.collection('visitors');

    // Get the user's IP and hash it.
    const userIP = getUserIP(event);
    const visitorFingerprint = hashIP(userIP);
    const now = new Date();

    // Build the initial document (the "pre‑update" data).
    // This document includes all fields that will later be updated after the simulation ends.
    const visitorDoc = {
      visitorFingerprint,    // The hashed IP, to later correlate multiple documents
      visitDate: now,        // The timestamp when the visitor loaded the site
      // Pre-update defaults:
      hasStarted: false,         // Will be set to true when the user clicks "start simulation"
      durationOfGame: null,      // To be updated later with the game duration
      naturalEnd: null,          // true if the game ended naturally (without a manual stop)
      valid: null,               // true if the game lasted long enough to count for high score
      endGameDate: null,         // Timestamp when the game ended (if applicable)
      portfolioValue: null,      // Final portfolio value after simulation
      buyHoldFinalValue: null,   // Final buy-and-hold portfolio value after simulation
      portfolioCAGR: null,       // User's CAGR (computed from simulation)
      buyHoldCAGR: null,         // Buy-and-hold CAGR (computed from simulation)
      buys: 0,                   // Number of buy actions (to be tallied)
      sells: 0                   // Number of sell actions (to be tallied)
    };

    // Insert a new document for this page load.
    const insertResult = await visitorsCollection.insertOne(visitorDoc);

    if (insertResult.acknowledged) {
      // Return the new document's _id so that the front end can save it for later updates.
      return {
        statusCode: 200,
        body: JSON.stringify({
          message: 'Visitor document created.',
          documentId: insertResult.insertedId
        }),
      };
    } else {
      return {
        statusCode: 500,
        body: JSON.stringify({ message: 'Failed to create visitor document.' }),
      };
    }
  } catch (error) {
    console.error('Error in createVisitorDocument function:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ message: 'Internal Server Error' }),
    };
  }
};